# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Tk-Bounded
version:      1.0.2
version_from: 
installdirs:  site
requires:
    attributes:                    0
    Carp:                          0
    Tk:                            5.8.7

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
